steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/trazy', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/trazy']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trazy'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trazy'
      - '--region'
      - 'asia-south1' # Bengaluru region closest
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'FRONTEND_URL=https://trazy.app,PORT=8080'

images:
  - 'gcr.io/$PROJECT_ID/trazy'
